#######################################
######        ELK STACVK          #####
#######################################
#-------------------------------------#


##############################
#####    elasticsearch    ####
##############################

apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: elasticsearch
  namespace: argocd
  ### ATENCAO: o parametro finalizer abaixo deleta dodos os pods e namespace criada pelo arquivo application.yml quando usado o comando kubectl delete application.yml
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  project: default  
  source:
    repoURL: 'git@github.com:uzieljr/pv-elk.git'
    path: elasticsearch
    targetRevision: HEAD
    helm:
      #releaseName: drone-server
      valueFiles:
        - values.yaml
  syncPolicy:   
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true


---

#############################
########    filebeat    ########
#############################

apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: filebeat
  namespace: argocd
  ### ATENCAO: o parametro finalizer abaixo deleta dodos os pods e namespace criada pelo arquivo application.yml quando usado o comando kubectl delete application.yml
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  project: default  
  source:
    repoURL: 'git@github.com:uzieljr/pv-elk.git'
    path: filebeat
    targetRevision: HEAD
    helm:
      #releaseName: drone-server
      valueFiles:
        - values.yaml
  syncPolicy:   
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true  

---

#############################
########    secret    #######
#############################

apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: kibana
  namespace: argocd
  ### ATENCAO: o parametro finalizer abaixo deleta dodos os pods e namespace criada pelo arquivo application.yml quando usado o comando kubectl delete application.yml
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  project: default  
  source:
    repoURL: 'git@github.com:uzieljr/pv-elk.git'
    path: kibana
    targetRevision: HEAD
    helm:
      #releaseName: drone-server
      valueFiles:
        - values.yaml
  syncPolicy:   
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true  